---
language: ruby
sudo: required
services:
  - docker
bundler_args: --without system_tests
script:
  - gem install bundler
  - bundle install --path vendor/bundle
  - bundle exec rake
matrix:
  include:
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 3.0" BEAKER_set="docker-centos6"
  - rvm: default
    env: PUPPET_VERSION="~> 4.0" BEAKER_set="docker-centos6-pc1"
  - rvm: 2.1.8
    env: PUPPET_VERSION="~> 3.0" BEAKER_set="docker-centos7"
  - rvm: default
    env: PUPPET_VERSION="~> 4.0" BEAKER_set="docker-centos7-pc1" DEPLOY_TO_FORGE=yes
deploy:
  provider: puppetforge
  user: tsystemsmms
  password:
    secure: kDb/MphFpzAsYezAQm1pn4m1DoiedeVpLg5FW8lHvyMut/kQQEC+u+8aktD0aaNtRxFqYVNNzV9APRR0a08oHmFXEdS3p+5qwxYxdHPeJue8YP0d7pUQCUZS31zCeltefRhoNy/4jMhxHGLgcSGQ738smKwJOrE+iWBM1BfQ2fMAMzOwfHSBScv/h0XsHA3n4NUTXKY3bSklA5JuzKlTfx9VkKx/R/OQsJssbyLAULEfoAQfZs7hUFeKShXm7d8SJ7ylvjmY/Cn/64vZmyAKe8pats7gK0RHsst3W0j5Ek+ekDF94xRrATGKbTpvmc+d/XV7bz/rouEegIYJ6HmOT9e8C+ZBok/dD7GU/cppnlNWmtv3zb3I4hH07mRA39tkSUke47zV/OtKqHMFwfXM+j3dVnPdJ+aHFfrzXRhsLTmmGh2LldiuLtQnWkLtMCjd/KO6WY+QX8fH/js/4I8buzcYioxC6GT8QA+TKMSav7z3O+HnvQ/1kh6AB1U6xr1u28CIt2O/s6Oyunp3OLyQNF/sXAseCAB5ENHpDEDJu5emM8vdoFZIJbks2DkqfqWbB6jeLPhcgdgaBhcigH1iBE4iaV1DU3P+eIwg8yAM0Mjahxk+JQgKQ6Qo+YQywdgzmbmi9A2HFHVix+AY6E2pw2EMLuyBQaGyt+QJTS89aWY=
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"

