HOSTS:
  centos-72-x64-ag1:
    roles:
      - agent
    platform: el-7-x86_64
    box: puppetlabs/centos-7.2-64-nocm
    hypervisor: vagrant
CONFIG:
  type: foss
  package_proxy: http://proxy.mms-dresden.de:8080
